Feature/sc 52
meaningfy-ws/ml-experiments pull request #16
Opened 2021-03-31 10:22 UTC by DanCh11

2021-03-31 20:51 UTC, costezki requested changes

2021-03-31 20:58 UTC, costezki reviewed
well done! This is a good start. Let's make some improvements.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def data_extraction(self, *args, **kwargs):
no, do not overwrite these methods, their implementation shall be inherited from PWDBBaseExperiment.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def data_validation(self, *args, **kwargs):
do not implement

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def data_preparation(self, *args, **kwargs):
idem.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +        fit_w2v_category = knn_w2v.fit(train_test_dataset['X_train'], train_test_dataset['y_train']['Category'])
revise the names of all the variables.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +        minio_ml_experiments.put_object("word2vec/KNN/knn_cateogry.pkl", pickle_w2v_category)
this shall be done with MLFlow. Start using it

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def model_evaluation(self, *args, **kwargs):
what about it?

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def model_validation(self, *args, **kwargs):
this can pass for now.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_knn_experiments.py
> +knn = KNNPWDBExperiment()
what is this? 
delete these two lines/.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_svm_experiment.py
> +        w2v_category = pickle.loads(minio.get_object(WORD2VEC_SVM_CATEGORY))
let's implement a function that takes a model from minio, evaluates it and stores the results in the mlflow.

2021-03-31 20:58 UTC, costezki commented on ml_experiments/services/pwdb_svm_experiment.py
> +        w2v_category = pickle.loads(minio.get_object(WORD2VEC_SVM_CATEGORY))
Programming challenge: shorten `model_evaluation` method to 5-10 lines max.

2021-03-31 20:58 UTC, costezki commented on requirements.txt
> +apache-airflow
mlflow too?

2021-04-01 06:20 UTC, DanCh11 commented on ml_experiments/services/pwdb_base_experiment.py
> +        train_test_dict = {"X_train": x_train, "X_test": x_test, "y_train": y_train, "y_test": y_test}
I think here is good, because we don't need to repeat the same action for train-test splitting over again for every algorithm

2021-04-01 06:23 UTC, DanCh11 commented on ml_experiments/services/pwdb_base_experiment.py
> +        convert_to_pickle = pickle.dumps(train_test_dict)
but how we can extract the data from this file and use it in algorithm training?

2021-04-01 06:26 UTC, DanCh11 commented on ml_experiments/services/pwdb_knn_experiments.py
> +    def model_evaluation(self, *args, **kwargs):
i have some questions about model_evaluation part that's why i didn't complete this stet yet

2021-04-01 06:28 UTC, DanCh11 commented on requirements.txt
> +apache-airflow
it's already in this file

2021-04-06 07:34 UTC, costezki reviewed
well done

2021-04-06 07:34 UTC, costezki commented on ml_experiments/services/pwdb_base_experiment.py
> +PWDB_REFACTORING_RULES = '''{
like so is much better

2021-04-06 07:34 UTC, costezki commented on ml_experiments/services/sc_wrangling/value_replacement.py
> +class MultiColumnLabelEncoder:
do we still need it? Didn't you discive that this is already implemented by sklearn?

2021-04-06 07:34 UTC, costezki commented on tests/minio_connection.py
> +class MinioTestFileCreation(MinioAdapter):
1. rename the class, following conventions from Clean Code CH2
2. this seems to be a Fake Minio Adapter, if so, call it accordingly

2021-04-06 07:34 UTC, costezki commented on tests/unit/test_prepare_pwdb_data.py
> +MINIO_ACCESS_KEY = '2zVld17bTfKk8iu0Eh9H74MywAeDV3WQ'
these secrets shall be taken from .env using a config file (implementing our practice)

2021-04-06 07:34 UTC, costezki commented on tests/unit/test_prepare_pwdb_data.py
> +    assert len(test_data_preparation) == len(expected_df)
you can also write a few assertions about the content

2021-04-06 07:49 UTC, DanCh11 commented on ml_experiments/services/sc_wrangling/value_replacement.py
> +class MultiColumnLabelEncoder:
LabelEncoder only takes a 1-d array as an argument.  It is quite easy to roll own label encoder that operates on multiple columns of our choosing, and returns a transformed dataframe

2021-04-06 16:59 UTC, costezki approved these changes
well done, keep on digging!!!

2021-04-06 17:00 UTC, merged