refactoring
meaningfy-ws/ml-experiments pull request #2
Opened 2021-02-12 13:16 UTC by DanCh11

changed evaluation matrix class into a function, added argument names and created unit tests

2021-02-12 14:15 UTC, cosletmihai requested changes

2021-02-12 14:15 UTC, cosletmihai commented on src/data_cleaner.py
> +def cleaning(text: str):
I'd recommend renaming this method to something more explicit.
ex: `prepare_text_for_<something>` or `remove_<something>_from_text`

> note! `<something>` should be substituted by what's more appropriate (`prepare_text_for_analysing`)

2021-02-12 14:15 UTC, cosletmihai commented on src/evaluation_metrics.py
> +def evaluation(actual: Series, prediction: ndarray, title: str):
I'd recommend renaming this method to something more explicit.
ex: `evaluate_series_with_<something>`

2021-02-12 14:15 UTC, cosletmihai commented on src/evaluation_metrics.py
> +    :title: column title of the DataFrame
according to [panda's documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) the names of the `columns` are called `labels` I suggest sticking to their naming to avoid confusion.

suggestion:
```python
def <method_name>(actual: Series, prediction: ndarray, label: str):
    '''
    ...
    :label: name of the column of the DataFrame to <what you're doing withing the method with that column>
    """
```

2021-02-12 14:15 UTC, cosletmihai commented on src/feature_selector.py
> +def reduce_array_column(df: DataFrame, column: str, new_column=None):
best practices recommend using more explicit variable names. I'd go with `data_frame` instead of `df`

2021-02-12 14:15 UTC, cosletmihai commented on src/feature_selector.py
> +def multi_label_column_to_binary_columns(df: DataFrame, column: str):
best practices recommend using more explicit variable names. I'd go with data_frame instead of df

2021-02-12 14:15 UTC, cosletmihai commented on src/pwdb_transformer.py
> +        :file_content: JSON file
update the documentation to reflect the method signature

2021-02-12 14:22 UTC, costezki approved these changes
nice improvements

2021-02-12 14:22 UTC, costezki commented on src/pwdb_transformer.py
> +def transform_json_to_csv(file: list, rules: str):
why is the file argument a list?

2021-02-12 14:22 UTC, costezki commented on src/pwdb_transformer.py
> +    with open(file) as file:
it certainly is not treated as a list :)

2021-02-12 14:22 UTC, costezki commented on src/pwdb_transformer.py
> +    jq_transformation_program = (".[] | "+str(rules)).replace("\n", "")
let's assume that the program is complete: that means that we shall not modify it (other than formatting).
This means that this  `".[] | "` should already be part of the program provided as a parameter, and we should not prepend it.

2021-02-12 14:22 UTC, costezki commented on tests/unit/test_data_cleaner.py
> +def test_data_cleaner():
let's try to improve this test.

2021-02-12 14:22 UTC, costezki commented on tests/unit/test_feature_selector.py
> +    expected_rows = pd.DataFrame({'col1': ['hello|world|Ave|Maria']})
this could be an assert

2021-02-12 14:22 UTC, costezki commented on tests/unit/test_pwdb_transformer.py
> +    assert len(df_rows) == expected_number_of_rows
this test could be written more concisely

2021-02-15 15:34 UTC, costezki approved these changes

2021-02-15 15:34 UTC, costezki commented on src/data_cleaner.py
>      text = re.split('\W+', text)
we should use a tokeniser here (punkt for example)

2021-02-15 15:35 UTC, cosletmihai approved these changes

2021-02-15 15:41 UTC, costezki commented on notebooks/pwdb/algorithms/KNN/target_groups.ipynb
>   "cells": [
<p>this is a test review</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/meaningfy-ws/ml-experiments/pull/2/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2021-02-15 17:20 UTC, merged